# This program calculates the number of calories
# generated by consuming fat and carbohydrates.

def main():
    
    # Get the number of fats consumed in grams.
    fats = get_fats()
    
    # Get the number of carbs consumed in grams.
    carbs = get_carbs()
    
    # Calculate and print the number of calories consumed.
    print('The member consumed', calculate_calories(fats, carbs), 'calories.')
    

# Data validation loop.
def data_validation(entry):
    if entry < 0:
        status = True
    else:
        status = False
    return status

# Obtain the number of fat grams consumed from the user.
def get_fats():
    
    # Obtain the number of fat grams consumed.
    fats = float(input('Please enter the number of fat grams consumed: '))
    
    # Validate the entry.
    while data_validation(fats):
        print('Please enter a number zero or greater.')
        fats = float(input('Please enter the number of fat grams consumed: '))
    
    # Return the value.
    return fats

# Obtain the number of carb grams consumed from the user.
def get_carbs():
    # Obtain the number of carb grams consumed.
    carbs = float(input('Please enter the number of carbohydrate grams consumed: '))
    
    # Validate the entry.
    while data_validation(carbs):
        print('Please enter a number zero or greater.')
        carbs = float(input('Please enter the number of carbohydrate grams consumed: '))
    
    # Return the value.
    return carbs

# Calculate the number of calories consumed.
def calculate_calories(fats, carbs):
    fat_calories = fats * 9
    carb_calories = carbs * 4
    return format(fat_calories + carb_calories, ',.1f')

# Call the main function.
main()
